# Generated by Django 5.2 on 2025-05-22 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catequista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, default='documentos/Catequistas/Photos/foto_default.jpg', help_text='Foto opcional del catequista.', null=True, upload_to='documentos/Catequistas/Photos/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Catequista',
                'verbose_name_plural': 'Catequistas',
            },
        ),
        migrations.CreateModel(
            name='CicloCatequesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciclo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(default='Sin descripción', max_length=255)),
                ('acta_bautizmo', models.BooleanField(default=False, verbose_name='Acta bautizmo')),
                ('acta_nacimiento', models.BooleanField(default=False, verbose_name='Acta nacimiento')),
                ('acta_comunion', models.BooleanField(default=False, verbose_name='Acta comunión')),
                ('acta_matrimonio', models.BooleanField(default=False, verbose_name='Acta Matrimonio')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Costo')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Padre',
                'verbose_name_plural': 'Padres',
            },
        ),
        migrations.CreateModel(
            name='Padrino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('documento_validacion', models.FileField(upload_to='documentos/Padrinos/')),
            ],
            options={
                'verbose_name': 'Padrino',
                'verbose_name_plural': 'Padrinos',
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('parroco', models.CharField(blank=True, max_length=150, null=True, verbose_name='Parroco')),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
            },
        ),
        migrations.CreateModel(
            name='CursoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo_maximo', models.PositiveIntegerField()),
                ('cerrado', models.BooleanField(default=False)),
                ('catequistas', models.ManyToManyField(blank=True, to='gestion.catequista')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ciclocatequesis')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cupo_maximo', models.PositiveIntegerField(default=20)),
                ('catequistas', models.ManyToManyField(blank=True, to='gestion.catequista')),
                ('curso_anual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cursoanual')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, default='documentos/Catequisandos/photos/default_photo.jpg', null=True, upload_to='documentos/Catequisandos/photos/')),
                ('fecha_nacimiento', models.DateField()),
                ('acta_bautismo', models.FileField(blank=True, null=True, upload_to='documentos/Catequisandos/actas_bautismo/')),
                ('acta_nacimiento', models.FileField(blank=True, null=True, upload_to='documentos/Catequisandos/actas_nacimiento/')),
                ('acta_comunion', models.FileField(blank=True, null=True, upload_to='documentos/Catequisandos/actas_comunion/')),
                ('acta_catequesis', models.FileField(blank=True, null=True, upload_to='documentos/Catequisandos/actas_catequesis/')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='gestion.padre')),
                ('padrino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='gestion.padrino')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.AddField(
            model_name='catequista',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.parroquia'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.estudiante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.grupo')),
            ],
            options={
                'unique_together': {('estudiante', 'grupo')},
            },
        ),
    ]
