# Generated by Django 5.2 on 2025-04-16 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(default='Sin descripción', max_length=255)),
                ('requisitos_documentos', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Padrino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('documento_validacion', models.FileField(upload_to='documentos/Padrinos/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('parroco', models.CharField(blank=True, max_length=150, null=True, verbose_name='Parroco')),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
            },
        ),
        migrations.CreateModel(
            name='Catequista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('representante', models.ForeignKey(blank=True, help_text='Seleccione al catequista que actúa como representante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catequistas_representados', to='gestion.catequista')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.parroquia')),
            ],
            options={
                'verbose_name': 'Catequista',
                'verbose_name_plural': 'Catequistas',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(default='Sin descripción', max_length=255)),
                ('max_estudiantes', models.PositiveIntegerField(default=20)),
                ('catequistas', models.ManyToManyField(blank=True, to='gestion.catequista')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.curso', to_field='codigo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='documentos/Catequisandos/photos/')),
                ('fecha_nacimiento', models.DateField()),
                ('acta_bautismo', models.FileField(blank=True, null=True, upload_to='documentos/Catequisandos/actas_bautismo/')),
                ('acta_nacimiento', models.FileField(blank=True, null=True, upload_to='documentos/Catequisandos/actas_nacimiento/')),
                ('acta_comunion', models.FileField(blank=True, null=True, upload_to='documentos/Catequisandos/actas_comunion/')),
                ('acta_catequesis', models.FileField(blank=True, null=True, upload_to='documentos/Catequisandos/actas_catequesis/')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='gestion.padre')),
                ('padrino', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiante', to='gestion.padrino')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('documentos_entregados', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.curso', to_field='codigo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.estudiante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.grupo', to_field='codigo')),
            ],
            options={
                'unique_together': {('estudiante', 'curso')},
            },
        ),
    ]
