# Generated by Django 5.2 on 2025-04-16 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catequista',
            name='representante',
            field=models.ForeignKey(blank=True, help_text='Seleccione al catequista que actúa como representante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catequistas_representados', to='gestion.catequista'),
        ),
        migrations.AddField(
            model_name='parroquia',
            name='parroco',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Parroco'),
        ),
        migrations.AlterField(
            model_name='catequista',
            name='actualizado_por',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='catequista',
            name='creado_por',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='actualizado_por',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='creado_por',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='actualizado_por',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='creado_por',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='actualizado_por',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='creado_por',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='padre',
            name='actualizado_por',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='padre',
            name='creado_por',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='padrino',
            name='actualizado_por',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='padrino',
            name='creado_por',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='actualizado_por',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='creado_por',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Representante',
        ),
    ]
